// app/layout.tsx
import type { Metadata } from "next";
import { Source_Sans_3 } from 'next/font/google';
import "./globals.css";
import { AuthProvider } from './context/AuthContext';
import { CartProvider } from './context/CartContext';

const sourceSansPro = Source_Sans_3({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ["latin"],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Farm2Table",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={sourceSansPro.className}>
      <body suppressHydrationWarning>
        <AuthProvider>
          <CartProvider>
            {children}
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}